<?xml version="1.0" ?>

<!--
Copyright (c) 2022, JRL-CARI CNR-STIIMA/UNIBS
Manuel Beschi manuel.beschi@unibs.it
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="finger" params="prefix base_name link_width link_height crank_length rod_length phalanx_length base_x base_z mimic_joint rot_z">
    <xacro:include filename="$(find parallel_2f_gripper)/urdf/box.xacro" />
    <xacro:include filename="$(find parallel_2f_gripper)/urdf/transmission.xacro" />
    <xacro:box name="${prefix}crank"  width="${link_width}" height="${link_height}" length="${crank_length}"/>
    <xacro:box name="${prefix}external_crank"  width="${link_width}" height="${link_height}" length="${crank_length}"/>
    <xacro:box name="${prefix}rod"  width="${link_width}" height="${link_height}" length="${rod_length}"/>
    <xacro:box name="${prefix}base_rod"  width="${link_width}" height="${link_height}" length="${rod_length}"/>
    <xacro:box name="${prefix}phalanx"     width="${link_width}" height="${link_height}" length="${phalanx_length}"/>

    <joint name="${prefix}finger_joint" type="revolute">
      <origin xyz="${0.5*(base_x+link_width)*cos(rot_z)} 0 ${base_z}" rpy="0 0 ${rot_z}"/>
      <parent link="${base_name}" />
      <child link="${prefix}crank" />
      <axis xyz="0 1 0" />
      <limit lower="${-asin(0.5*base_x/crank_length)}" upper="${1}" velocity="5.0" effort="50" />

      <xacro:unless value="${mimic_joint == ''}">
        <mimic joint="${mimic_joint}" multiplier="1" offset="0" />
      </xacro:unless>
    </joint>


    <joint name="${prefix}joint_2_5" type="fixed">
      <origin xyz="0 0 0" rpy="0 ${-pi/2} 0"/>
      <parent link="${prefix}rod" />
      <child link="${prefix}phalanx" />
      <axis xyz="0 1 0" />
    </joint>

      <joint name="${prefix}joint_1_2" type="revolute">
        <origin xyz="0 0 ${crank_length}" rpy="0 ${pi/2} 0"/>
        <parent link="${prefix}crank" />
        <child link="${prefix}rod" />
        <axis xyz="0 1 0" />
        <limit lower="${-pi}" upper="${pi}" velocity="2.0" effort="10" />
        <mimic joint="${prefix}finger_joint" multiplier="-1" offset="0" />
      </joint>


      <joint name="${prefix}joint_2_3" type="revolute">
        <origin xyz="0 0 ${rod_length}" rpy="0 ${pi/2} 0"/>
        <parent link="${prefix}rod" />
        <child link="${prefix}external_crank" />
        <axis xyz="0 1 0" />
        <limit lower="${-pi}" upper="${pi}" velocity="2.0" effort="10" />
        <mimic joint="${prefix}finger_joint" multiplier="1" offset="0" />
      </joint>


        <joint name="${prefix}joint_3_4" type="revolute">
          <origin xyz="0 0 ${crank_length}" rpy="0 ${pi/2} 0"/>
          <parent link="${prefix}external_crank" />
          <child link="${prefix}base_rod" />
          <axis xyz="0 1 0" />
          <limit lower="${-pi}" upper="${pi}" velocity="2.0" effort="10" />
          <mimic joint="${prefix}finger_joint" multiplier="-1" offset="0" />
        </joint>

        <link name="${prefix}tip"/>
        <joint name="${prefix}tip_joint" type="fixed">
          <origin xyz="${-0.5*link_width} 0 ${phalanx_length}" rpy="0 0 0"/>
          <parent link="${prefix}phalanx" />
          <child link="${prefix}tip" />
        </joint>


      <gazebo>
        <joint name="${prefix}joint_4_1" type="revolute">
         <parent>${prefix}base_rod</parent>
         <child>${prefix}crank</child>
         <pose relative_to="${prefix}base_rod">0 0 ${rod_length}   0 ${pi/2} 0</pose>
         <axis>
           <xyz>0 1 0</xyz>
         </axis>
       </joint>

       <joint name="${prefix}joint_0_4" type="revolute">
        <parent>${base_name}</parent>
        <child>${prefix}base_rod</child>
        <pose relative_to="${base_name}">${(0.5*(base_x+link_width)+rod_length)*cos(rot_z)} 0 ${base_z} 0 0 ${rot_z}</pose>
        <axis>
          <xyz>0 1 0</xyz>
        </axis>
      </joint>
      </gazebo>

      <gazebo reference="${prefix}phalanx">
        <self_collide>1</self_collide>
        <kp>100000</kp>
        <kd>200</kd>
        <mu1>2</mu1>
        <mu2>2</mu2>
      </gazebo>


    </xacro:macro>
</robot>
