$(arg gripper_name):
  start_position: [0,0,0.1]
  # start_orientation: [0,0,0]
  start_orientation: [1.5708,0,0]
  fixed: 0    # 1 to fix robot to world, 0 to spawn it unfixed
  foulder_path: '/home/gauss/projects/personal_ws/src/parallel_2f_gripper/urdf'
  xacro_file_name: 'gripper_pybullet'   # an urdf file with the same name will be generated
  controlled_joint_name: ['$(arg prefix)right_finger_joint'] # right_finger_joint     fingers_joint #,'left_finger_joint']
  joint_control_mode : 'position' # positon (which is in fact POSITION_VELOCITY_PD), velocity, torque and pd.
  constraints:
    - piloted_joint_name: ['$(arg prefix)left_finger_joint']
      parent_body: '$(arg gripper_name)'
      parent_link: 'right_crank'
      child_body: '$(arg gripper_name)'
      child_link: 'left_crank'
      type: 'gear'             # joint type: prismatic, fixed, point2point, gear
      gear_ratio: -1
      erp: 5
      # erp: 0.1
      axis: [0,1,0]                   # joint axis, in child link frame
      parent_frame_position: [0,0,0]  # position of the joint frame relative to parent center of mass frame.
      child_frame_position: [0,0,0]   # position of the joint frame relative to a given child center of mass frame (or world origin if no child specified)
      parent_frame_orientation: [0,0,0,1] # the orientation of the joint frame relative to parent center of mass coordinate frame
      child_frame_orientation: [0,0,0,1]  # the orientation of the joint frame relative to the child center of mass coordinate frame (or world origin frame if no child specified)
      max_force: 10000

    - parent_body: '$(arg gripper_name)'
      parent_link: 'gripper_base'
      child_body: '$(arg gripper_name)'
      child_link: 'right_base_rod'
      type: 'fixed'             # joint type: prismatic, fixed, point2point, gear
      axis: [0,0,0]                   # joint axis, in child link frame
      parent_frame_position: [0.105, 0.000, 0.050] # position of the joint frame relative to parent center of mass frame.
      parent_frame_orientation: [0.000, -0.707, 0.000, 0.707] # the orientation of the joint frame relative to parent center of mass coordinate frame
      child_frame_position: [0,0,0]   # position of the joint frame relative to a given child center of mass frame (or world origin if no child specified)
      child_frame_orientation: [0,0,0,1]  # the orientation of the joint frame relative to the child center of mass coordinate frame (or world origin frame if no child specified)
      max_force: 100000
    - parent_body: '$(arg gripper_name)'
      parent_link: 'gripper_base'
      child_body: '$(arg gripper_name)'
      child_link: 'left_base_rod'
      type: 'fixed'             # joint type: prismatic, fixed, point2point, gear
      axis: [0,0,0]                   # joint axis, in child link frame
      parent_frame_position: [-0.105, 0.000, 0.050] # position of the joint frame relative to parent center of mass frame.
      parent_frame_orientation: [0.707, -0.000, 0.707, 0.000] # the orientation of the joint frame relative to parent center of mass coordinate frame
      child_frame_position: [0,0,0]   # position of the joint frame relative to a given child center of mass frame (or world origin if no child specified)
      child_frame_orientation: [0,0,0,1]  # the orientation of the joint frame relative to the child center of mass coordinate frame (or world origin frame if no child specified)
      max_force: 100000
  link_dynamics:
    - link_name: 'right_phalanx'
      lateral_friction: 30
      spinning_friction: 0.1
      rolling_friction: 0.1
      contact_stiffness: 100000
      contact_damping: 1
      linear_damping: 0
      angular_damping: 0
      friction_anchor: 1
    - link_name: 'left_phalanx'
      lateral_friction: 30
      spinning_friction: 0.1
      rolling_friction: 0.1
      contact_stiffness: 100000
      contact_damping: 1
      linear_damping: 0
      angular_damping: 0
      friction_anchor: 1
    - link_name: 'right_crank'
      lateral_friction: 30
      spinning_friction: 0.1
      rolling_friction: 0.1
      contact_stiffness: 100000
      contact_damping: 1
      linear_damping: 0
      angular_damping: 0
      friction_anchor: 1
    - link_name: 'left_crank'
      lateral_friction: 30
      spinning_friction: 0.1
      rolling_friction: 0.1
      contact_stiffness: 100000
      contact_damping: 1
      linear_damping: 0
      angular_damping: 0
      friction_anchor: 1
